const P=[
['Capítulo 7','Poema visual','Quando palavras são organizadas para formar o desenho de um animal, que recurso está sendo usado?',['Poema visual','Receita','Notícia'],0,'As palavras também podem formar uma imagem.','🔤  🔤  🔤<br>🔤🔤🔤🔤<br>🔤  🔤'],
['Capítulo 7','Imagem formada','No texto estudado, as palavras repetidas formam a imagem de qual animal?',['Jacaré','Cavalo','Peixe'],0,'A imagem formada é a de um jacaré.','🔤 🔤 🔤 🔤 🔤<br><small>Observe a ideia de palavras formando uma figura.</small>'],
['Capítulo 7','Sentido divertido','No poema, a ideia de um “animal letrado” brinca principalmente com o fato de ele ser...',['feito com letras','um animal que usa chapéu','um animal muito veloz'],0,'O texto brinca com letras formando o animal.','🔤 + 🖼️'],
['Capítulo 7','Autor','Quem escreveu o poema visual estudado no início do capítulo 7?',['Sérgio Capparelli','Renata Bueno','Gloria Kirinus'],0,'O poema é de Sérgio Capparelli.','✍️ 📖'],
['Capítulo 7','Título e texto','Um bom título deve...',['ter relação com o texto','ser sempre uma pergunta','ter apenas uma palavra'],0,'O título ajuda a antecipar o assunto do texto.','📖 ❓'],
['Capítulo 7','Troca de letras','Qual palavra surge ao trocar o B de BOLA por M?',['MOLA','MALA','MULA'],0,'BOLA → MOLA.','BOLA<br><strong>B → M</strong>'],
['Capítulo 7','Troca de letras','Qual grupo segue o mesmo padrão de troca da primeira letra?',['LATA, MATA, PATA, RATA','LATA, LAGO, LUPA, LIXO','MALA, MESA, MICO, MURO'],0,'A parte ATA permanece e muda a primeira letra.','_ATA &nbsp; _ATA &nbsp; _ATA &nbsp; _ATA'],
['Capítulo 7','Organizando letras','As letras A, L, O, B podem formar qual palavra?',['BOLA','LOBAA','ALBO'],0,'A organização correta forma BOLA.','A &nbsp; L &nbsp; O &nbsp; B'],
['Capítulo 7','Sílaba inicial','Qual é a sílaba inicial de MOCHILA?',['MO','CHI','LA'],0,'MO-CHI-LA começa por MO.','🎒'],
['Capítulo 7','Sílaba inicial','Qual é a sílaba inicial de LÁPIS?',['LÁ','PIS','LA-PIS'],0,'LÁ-PIS começa por LÁ.','✏️'],
['Capítulo 7','Sílaba inicial','Qual é a sílaba inicial de BORRACHA?',['BO','RRA','CHA'],0,'BO-RRA-CHA começa por BO.','🧽'],
['Capítulo 7','Sílaba inicial','Qual é a sílaba inicial de TESOURA?',['TE','SOU','RA'],0,'TE-SOU-RA começa por TE.','✂️'],
['Capítulo 7','Sílaba inicial','Qual é a sílaba inicial de PANELA?',['PA','NE','LA'],0,'PA-NE-LA começa por PA.','🍲'],
['Capítulo 7','Consoante + vogal','Qual separação está correta para SAPO?',['SA-PO','SAP-O','S-A-PO'],0,'SA e PO são sílabas formadas por consoante + vogal.','🐸 <small>Separe a palavra em sílabas.</small>'],
['Capítulo 7','Família com S','Qual palavra começa com a sílaba SE?',['SETE','SINO','SUCO'],0,'SE-TE começa com SE.','SE…'],
['Capítulo 7','Família com S','Qual palavra começa com a sílaba SI?',['SINO','SOPA','SAPO'],0,'SI-NO começa com SI.','SI…'],
['Capítulo 7','Família com S','Qual palavra começa com a sílaba SO?',['SOPA','SETE','SUCO'],0,'SO-PA começa com SO.','SO…'],
['Capítulo 7','Família com S','Qual palavra começa com a sílaba SU?',['SUCO','SINO','SAPO'],0,'SU-CO começa com SU.','SU…'],
['Capítulo 7','Poema que conta história','O texto “Na volta da escola” é melhor classificado como...',['um poema que conta uma história','uma notícia','uma receita'],0,'O texto é um poema que apresenta uma pequena história.','🚌 📖'],
['Capítulo 7','Quantidade de crianças','Se havia 14 crianças além de Ian, quantas crianças havia ao todo?',['15','14','16'],0,'São 14 crianças mais Ian, totalizando 15.','🚌 👧🧒<br><small>Use a informação do enunciado para calcular.</small>'],
['Capítulo 7','Ações na van','Segundo o poema, o que as crianças faziam durante a volta da escola?',['cantavam e brincavam','dormiam e estudavam','cozinhavam e desenhavam'],0,'O poema informa que elas voltavam cantando e brincando.','🚌 🏫 → 🏠'],
['Capítulo 7','Personagens e casas','Quais nomes aparecem como paradas na volta da escola?',['Luís Felipe, Clarinha e Ian','Bruna, Brenda e Pedro','Ana, Bia e João'],0,'Esses são os nomes citados nas paradas.','🏠 🏠 🏠'],
['Capítulo 7','Poema-problema','Se 15 crianças fossem divididas igualmente entre 3 casas, quantas ficariam em cada casa?',['5','4','6'],0,'15 dividido igualmente em 3 grupos dá 5.','👧🧒 → 🏠 🏠 🏠'],
['Capítulo 7','Consoantes e vogais','Na palavra MOLECADA, a letra M é...',['consoante','vogal','sílaba'],0,'M é uma consoante.','<strong>M</strong>OLECADA'],
['Capítulo 7','Consoantes e vogais','Na palavra MOLECADA, a letra O é...',['vogal','consoante','palavra'],0,'O é uma vogal.','M<strong>O</strong>LECADA'],
['Capítulo 7','Palavra com letra repetida','Qual palavra de 4 letras tem uma letra repetida?',['CASA','RIO','VAN'],0,'Em CASA, a letra A aparece duas vezes.','🔤 🔎<br><small>Compare as alternativas.</small>'],
['Capítulo 7','Palavra que termina com A','Qual palavra tem 6 letras e termina com A?',['PARADA','NÚMERO','FELIPE'],0,'PARADA tem 6 letras e termina em A.','⬜⬜⬜⬜⬜⬜ → A'],
['Capítulo 7','Palavra que começa com N','Qual palavra tem 6 letras e começa com N?',['NÚMERO','PARADA','FELIPE'],0,'NÚMERO começa com N e tem 6 letras.','N → ⬜⬜⬜⬜⬜⬜'],
['Capítulo 7','Palavra que começa com F','Qual palavra tem 6 letras e começa com F?',['FELIPE','PARADA','NÚMERO'],0,'FELIPE começa com F e tem 6 letras.','F → ⬜⬜⬜⬜⬜⬜'],
['Capítulo 7','Trava-língua','Trava-língua é um texto criado principalmente para...',['brincar com sons e palavras difíceis de dizer rápido','ensinar uma receita','dar uma notícia'],0,'Ele explora repetições de sons e palavras.','👄 💬 ⚡'],
['Capítulo 8','Bilhete','Um bilhete é geralmente...',['uma mensagem curta escrita para alguém','um texto longo de enciclopédia','uma lista de compras obrigatoriamente'],0,'Bilhetes são mensagens curtas e diretas.','📝 💬'],
['Capítulo 8','Onde foi escrito','No exemplo estudado, o bilhete aparece escrito em qual suporte?',['saco de papel','jornal','livro'],0,'O bilhete está escrito em um saco de papel.','📝 ❓'],
['Capítulo 8','Pequeno Planta','Pelas pistas do bilhete, “Pequeno Planta” é...',['nome de uma empresa','nome de uma criança','título de um poema'],0,'A expressão identifica a empresa que envia a mensagem.','PEQUENO PLANTA<br><small>Use as pistas do texto.</small>'],
['Capítulo 8','Comunicação','Qual conjunto apresenta formas de comunicação?',['gestos, imagens, símbolos e palavras','apenas números e contas','somente livros'],0,'Podemos nos comunicar de várias formas.','💬 ❓'],
['Capítulo 8','Carta','Quem escreve uma carta é chamado de...',['remetente','destinatário','personagem principal'],0,'Remetente é quem envia ou escreve a carta.','✍️ ✉️'],
['Capítulo 8','Carta','Quem recebe uma carta é chamado de...',['destinatário','remetente','narrador'],0,'Destinatário é quem recebe a carta.','✉️ 📬'],
['Capítulo 8','Carta para El Niño','Quem escreveu o texto “Carta para El Niño”?',['Gloria Kirinus','Sérgio Capparelli','Renata Bueno'],0,'A autora é Gloria Kirinus.','📖 ✍️ ❓'],
['Capítulo 8','Sapo-jururu','No texto, por que o sapo-jururu berra?',['porque sente muito frio','porque está com fome','porque perdeu um brinquedo'],0,'O texto relaciona o berro do sapo ao frio.','🐸 💬'],
['Capítulo 8','Sentido de jururu','Pelo contexto, “jururu” significa...',['triste ou desanimado','muito alegre','muito rápido'],0,'Jururu indica tristeza ou desânimo.','🐸 ❓'],
['Capítulo 8','Sílabas repetidas','Qual palavra apresenta uma sílaba repetida?',['BATATA','PATINETE','MAMADEIRA'],0,'BA-TA-TA repete a sílaba TA.','🔁 🔤<br><small>Procure uma sílaba que apareça duas vezes.</small>'],
['Capítulo 8','Sem sílaba repetida','Qual palavra NÃO apresenta repetição de uma sílaba inteira?',['PATINETE','BATATA','COCO'],0,'PA-TI-NE-TE não repete uma sílaba inteira; BATATA repete TA e COCO repete CO.','🔤 🔎<br><small>Separe mentalmente cada alternativa em sílabas.</small>']
];
function visualPort(v){return `<div class="port-visual">${v}</div>`}
function montarPort(){const g=document.getElementById('gridPort');g.innerHTML='';P.forEach((q,i)=>{const c=document.createElement('div');c.className='qcard';c.dataset.grupo=q[0];c.innerHTML=`<div class="qhead"><h3>${i+1}. ${q[1]}</h3><div class="tags"><span class="tag porttag">${q[0]}</span></div></div><div class="visual"><div class="canvas">${visualPort(q[6])}</div></div><div class="body"><p class="question">${q[2]}</p>${q[3].map((x,j)=>`<label class="option"><input type="radio" name="p${i}" value="${j}"> ${String.fromCharCode(65+j)}) ${x}</label>`).join('')}<div class="feedback"></div></div>`;g.appendChild(c)})}
function filtrarPort(g,b){document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('#gridPort .qcard').forEach(c=>c.style.display=g==='Todos'||c.dataset.grupo===g?'':'none')}
function corrigirPort(){let ac=0,rp=0,c7=0,c8=0;document.querySelectorAll('#gridPort .qcard').forEach((c,i)=>{c.querySelectorAll('.option').forEach(x=>x.classList.remove('correct','wrong'));const q=P[i],m=c.querySelector('input:checked'),f=c.querySelector('.feedback');if(!m){f.style.display='block';f.innerHTML='⚠️ <strong>Não respondida.</strong>';return}rp++;if(+m.value===q[4]){ac++;q[0]==='Capítulo 7'?c7++:c8++;m.closest('.option').classList.add('correct');f.innerHTML='✅ <strong>Correto!</strong> '+q[5]}else{m.closest('.option').classList.add('wrong');c.querySelectorAll('.option')[q[4]].classList.add('correct');f.innerHTML='❌ <strong>Vamos revisar:</strong> '+q[5]}f.style.display='block'});const total=P.length,tot7=P.filter(q=>q[0]==='Capítulo 7').length,tot8=P.filter(q=>q[0]==='Capítulo 8').length;const r=document.getElementById('resultPort');r.innerHTML=`Respondidas: <strong>${rp}/${total}</strong><br>Capítulo 7: <strong>${c7}/${tot7}</strong> | Capítulo 8: <strong>${c8}/${tot8}</strong><br>Total: <strong>${ac}/${total}</strong><br>${ac>=36?'🌟 Excelente!':ac>=30?'👏 Muito bom!':ac>=22?'🙂 Bom trabalho! Revise os erros.':'💪 Continue treinando e tente novamente.'}`;r.style.display='block';r.scrollIntoView({behavior:'smooth',block:'center'})}
function refazerPort(){document.querySelectorAll('#quizPort input[type=radio]').forEach(x=>x.checked=false);document.querySelectorAll('#gridPort .option').forEach(x=>x.classList.remove('correct','wrong'));document.querySelectorAll('#gridPort .feedback').forEach(x=>{x.style.display='none';x.innerHTML=''});document.getElementById('resultPort').style.display='none'}
montarPort();